name: Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.SSH_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}

        run: |
          echo "$PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key ${USER_NAME}@${HOSTNAME} "
          ./deploy.sh ${DB_PASSWORD} ${GITHUB_TOKEN}
          "
