name: Backend CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        # This makes all `run` steps execute in the backend directory
        working-directory: ./backend
        
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
    
    # Install dependencies including TypeScript
    - name: Install dependencies
      run: npm ci
      
    # TypeScript type checking
    - name: Type check
      run: npm run type-check # Assuming you have this script in package.json
      
    # Build step that includes TypeScript compilation
    - name: Build
      run: npm run build
      
    # Run tests (assuming they're set up to handle TypeScript)
    - name: Test
      run: npm test
